version: '3'

services:
  nginx:
    image: nginx
    env_file:
      - .env
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./back:/app
      - ./v-log:/log
    ports:
      - '${SERVER_EXTERNAL_PORT}:80'

  php:
    environment:
      PHP_IDE_CONFIG: 'serverName=combo'
    build: ./docker
    env_file:
      - .env
    volumes:
      - ./back:/app
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

  db:
    image: mariadb
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'ok'
    env_file:
      - .env
    volumes:
      - ./v-db:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '${DATABASE_EXTERNAL_PORT}:3306'

  pma:
    image: phpmyadmin
    environment:
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '${PMA_EXTERNAL_PORT}:80'
