CREATE TABLE IF NOT EXISTS `accounts` (
  `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `login` TINYTEXT,
  `email` TINYTEXT,
  `password` TINYTEXT
);
